spring:
  application:
    name: BackenedUserCenter
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yupiuniverse
    username: root
    password: 12345
server:
  port: 8080
